### ISSUE TITLE
./stop.sh not working

### ISSUE THREAD

**Issue by akashk92** [KotlinCraft/modern-java-and-kotlin-tutorials#4]
I run ./startup.sh, and everything works fine.
When I run ./stop.sh to stop all up services, i get following error

> $ ./stop.sh 
cat: notifications-service/notification-micro-service.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
cat: eureka-server/eureka-server.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
cat: api-service/application.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

Any fix or siggestions?

**Comment by Qkyrie** [comment]
What environment are you using?

Would it be possible to tell me if the pid files are being created on startup?
